export const PlantDictionary = {
    "Tomato (Lycopersicon esculentum)": 5021,
    "Tomato (Solanum lycopersicum)": 8759,
    "Cucumber (Cucumis sativus)": 2251,
    "Sweet potato (Ipomoea batatas)": 4302,  
    "Potato (Solanum tuberosum)": 7409,
    "Onion (Allium cepa)": 667,
    "scallion (Allium fistulosum)": 671,
    "Garlic (Allium sativum)": 682,
    "Strawberry (Fragaria Cavendish)": 3017,
    "Strawberry (Fragaria Dunlap)": 3018,
    "Strawberry (Fragaria Earliglo)": 3019,
    "Akane Apple": 351,
    "Ambrosia Apple": 352,
    "Braeburn Apple": 354,
    "Chehalis Apple": 356,
    "Cortland Apple": 357
    "Banana (Musa acuminata)": 5280,
    "Mandarin orange (Citrus reticulata)": 1893,
    "Navel orange (Citrus sinensis)": 1895,
    "Lemon (Citrus limon)": 1888,
    "Peach (Prunus persica)": 6368,
    "Cherry (Prunus avium)": 6333,
    "Blueberry (Vaccinium corymbosum)": 8040,
    "Blueberry (Vaccinium Chippewa)": 8041,
    "Raspberry (Rubus idaeus)": 6965,
    "Blackberry (Rubus fruticosus)": 6954,
    "lettuce (Lactuca sativa)": 4626,
    "spinach (Spinacia oleracea)": 7468,
    "cabbage (Brassica oleracea)": 1322,
    "broccoli (Brassica oleracea)": 1327,
    "blueberries (Vaccinium corymbosum)": 8040,
    "raspberries (Rubus idaeus)": 6956,
};